src/Entity/Patient.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\PatientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: PatientRepository::class)]
class Patient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastName;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstName;

    #[ORM\Column(type: 'date')]
    private $birthDate;

    #[ORM\Column(type: 'string', length: 255)]
    private $bloodGroup;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $size;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $weight;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updatedAt;

    #[ORM\ManyToOne(inversedBy: 'patients')]
    private ?User $user = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private $antMedic;

    #[ORM\Column(type: 'text', nullable: true)]
    private $allergies;

    #[ORM\Column(type: 'text', nullable: true)]
    private $vaccins;

    #[ORM\Column(type: 'text', nullable: true)]
    private $tabac;

    #[ORM\Column(type: 'text', nullable: true)]
    private $alcool;

    #[ORM\Column(type: 'text', nullable: true)]
    private $stupefiants;

    #[ORM\Column(type: 'text', nullable: true)]
    private $sommeil;

    #[ORM\Column(type: 'text', nullable: true)]
    private $alimentation;

    #[ORM\Column(type: 'text', nullable: true)]
    private $activitePhysique;

    #[ORM\Column(type: 'text', nullable: true)]
    private $employeur;



    #[ORM\OneToMany(targetEntity: EmergencyContact::class, mappedBy: 'patient', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private $emergencyContacts;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->emergencyContacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstName;
    }

    public function setFirstname(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthdate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getBloodGroup(): ?string
    {
        return $this->bloodGroup;
    }

    public function setBloodGroup(string $bloodGroup): self
    {
        $this->bloodGroup = $bloodGroup;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getWeight(): ?int
    {
        return $this->weight;
    }

    public function setWeight(int $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getAntMedic(): ?string
    {
        return $this->antMedic;
    }

    public function setAntMedic(?string $antMedic): self
    {
        $this->antMedic = $antMedic;

        return $this;
    }

    public function getAllergies(): ?string
    {
        return $this->allergies;
    }

    public function setAllergies(?string $allergies): self
    {
        $this->allergies = $allergies;

        return $this;
    }

    public function getVaccins(): ?string
    {
        return $this->vaccins;
    }

    public function setVaccins(?string $vaccins): self
    {
        $this->vaccins = $vaccins;

        return $this;
    }

    public function getTabac(): ?string
    {
        return $this->tabac;
    }

    public function setTabac(?string $tabac): self
    {
        $this->tabac = $tabac;

        return $this;
    }

    public function getAlcool(): ?string
    {
        return $this->alcool;
    }

    public function setAlcool(?string $alcool): self
    {
        $this->alcool = $alcool;

        return $this;
    }

    public function getStupefiants(): ?string
    {
        return $this->stupefiants;
    }

    public function setStupefiants(?string $stupefiants): self
    {
        $this->stupefiants = $stupefiants;

        return $this;
    }

    public function getSommeil(): ?string
    {
        return $this->sommeil;
    }

    public function setSommeil(?string $sommeil): self
    {
        $this->sommeil = $sommeil;

        return $this;
    }

    public function getAlimentation(): ?string
    {
        return $this->alimentation;
    }

    public function setAlimentation(?string $alimentation): self
    {
        $this->alimentation = $alimentation;

        return $this;
    }

    public function getActivitePhysique(): ?string
    {
        return $this->activitePhysique;
    }

    public function setActivitePhysique(?string $activitePhysique): self
    {
        $this->activitePhysique = $activitePhysique;

        return $this;
    }

    public function getEmployeur(): ?string
    {
        return $this->employeur;
    }

    public function setEmployeur(?string $employeur): self
    {
        $this->employeur = $employeur;

        return $this;
    }


    public function getEmergencyContacts(): Collection
    {
        return $this->emergencyContacts;
    }

    public function addEmergencyContact(EmergencyContact $contact): self
    {
        if (!$this->emergencyContacts->contains($contact)) {
            $this->emergencyContacts[] = $contact;
            $contact->setPatient($this);
        }

        return $this;
    }

    public function removeEmergencyContact(EmergencyContact $contact): self
    {
        if ($this->emergencyContacts->contains($contact)) {
            $this->emergencyContacts->removeElement($contact);
            // set the owning side to null (unless already changed)
            if ($contact->getPatient() === $this) {
                $contact->setPatient(null);
            }
        }

        return $this;
    }


    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    private function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/PatientType.php
<?php

namespace App\Form;

use App\Entity\Patient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class PatientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('lastname', TextType::class, ['label' => 'Nom'])
            ->add('firstName', TextType::class, ['label' => 'Prénom'])
            ->add('birthdate', DateType::class, [
                'label' => 'Date de naissance',
                'widget' => 'single_text'
            ])
            ->add('bloodgroup', ChoiceType::class, [
                'label' => 'Groupe sanguin',
                'required' => false,
                'choices' => [
                    '' => '',
                    'A+' => 'A+',
                    'A-' => 'A-',
                    'B+' => 'B+',
                    'B-' => 'B-',
                    'AB+' => 'AB+',
                    'AB-' => 'AB-',
                    'O+' => 'O+',
                    'O-' => 'O-',
                ],
            ])
            ->add('size', IntegerType::class, [
                'label' => 'Taille (cm)',
                'required' => false,
            ])
            ->add('weight', IntegerType::class, [
                'label' => 'Poids (kg)',
                'required' => false,
            ])
            ->add('emergencyContacts', CollectionType::class, [
                'entry_type' => EmergencyContactType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'label' => false,
                'required' => false,
            ])
            ->add('antMedic', TextareaType::class, [
                'label' => 'ANT Médic',
                'required' => false,
            ])
            ->add('allergies', TextareaType::class, [
                'label' => 'ALLERGIE',
                'required' => false,
            ])
            ->add('vaccins', TextareaType::class, [
                'label' => 'VACCINS',
                'required' => false,
            ])
            ->add('tabac', TextareaType::class, [
                'label' => 'TABAC',
                'required' => false,
            ])
            ->add('alcool', TextareaType::class, [
                'label' => 'ALCOOL',
                'required' => false,
            ])
            ->add('stupefiants', TextareaType::class, [
                'label' => 'STUPÉFIANTS',
                'required' => false,
            ])
            ->add('sommeil', TextareaType::class, [
                'label' => 'SOMMEIL',
                'required' => false,
            ])
            ->add('alimentation', TextareaType::class, [
                'label' => 'ALIMENTATION',
                'required' => false,
            ])
            ->add('activitePhysique', TextareaType::class, [
                'label' => 'ACTIVITÉ PHYSIQUE',
                'required' => false,
            ])
            ->add('employeur', TextareaType::class, [
                'label' => 'EMPLOYEUR',
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Patient::class,
        ]);
    }
}

src/Controller/PatientsController.php
<?php

namespace App\Controller;

use App\Entity\Patient;
use App\Form\PatientType;
use App\Entity\EmergencyContact;
use App\Repository\PatientRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Persistence\ManagerRegistry;


#[Route('/patients')]
class PatientsController extends AbstractController
{
    public function __construct(private ManagerRegistry $doctrine)
    {
    }

    #[Route('/', name: 'app_patients_index', methods: ['GET'])]
    public function index(PatientRepository $patientRepository): Response
    {
        $letters = range('A', 'Z');
        $patients = $patientRepository->findAll();

        return $this->render('patients/index.html.twig', [
            'letters' => $letters,
            'patients' => $patients,
        ]);
    }

    #[Route('/letter/{letter}', name: 'app_patients_by_letter', methods: ['GET'])]
    public function patientsByLetter(PatientRepository $patientRepository, string $letter): Response
    {
        $patients = $patientRepository->findByLetter($letter);

        return $this->render('patients/by_letter.html.twig', [
            'patients' => $patients,
            'letter' => $letter,
        ]);
    }

    #[Route('/new', name: 'app_patient_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $patient = new Patient();

        $form = $this->createForm(PatientType::class, $patient); // Utilisez PatientType
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($patient);
            $entityManager->flush();

            return $this->redirectToRoute('app_patients_index');
        }

        return $this->render('patients/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    #[Route('/details-patient/{id}', name: 'app_patients_show', methods: ['GET'])]
    public function show(Patient $patient): Response
    {
        return $this->render('patients/show.html.twig', [
            'patient' => $patient,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_patients_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Patient $patient, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PatientType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_patients_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('patients/edit.html.twig', [
            'patient' => $patient,
            'form' => $form->createView(),
            'emergencyContacts' => $patient->getEmergencyContacts()
        ]);
    }
    #[Route('/patients/{id}/delete/{contactID}', name: 'app_patients_supprimer_contact')]
    public function deleteEmergencyContact(Patient $patient, EmergencyContact $contactID, EntityManagerInterface $entityManager): Response
    {
        // Vérifier que le contact d'urgence est bien associé au patient
        if ($patient->getEmergencyContacts()->contains($contactID)) {
            $patient->removeEmergencyContact($contactID);
            $entityManager->remove($contactID);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_patients_edit', ['id' => $patient->getId()]);
    }

    // Modifiez votre route pour autoriser les requêtes GET et POST
    #[Route('/supprimer-patient/{id}', name: 'app_patients_delete', methods: ['GET', 'POST'])]
    public function delete(Request $request, Patient $patient, EntityManagerInterface $entityManager): Response
    {
        // Vérifiez si la requête est POST
        if ($request->isMethod('POST')) {
            // Vérifiez le jeton CSRF
            if ($this->isCsrfTokenValid('delete' . $patient->getId(), $request->request->get('_token'))) {
                $entityManager->remove($patient);
                $entityManager->flush();
            }

            $this->addFlash('success', 'Patient supprimé avec succès');

            return $this->redirectToRoute('app_patients_index', [], Response::HTTP_SEE_OTHER);
        }

        // Si la requête n'est pas POST, redirigez ou renvoyez une erreur, selon votre logique
        // Par exemple, vous pouvez rediriger vers une autre page avec un message d'erreur
        return $this->redirectToRoute('app_patients_index');
    }
}

templates/patients/_delete_form.html.twig
<form method="post" action="{{ path('app_patients_delete', {'id': patient.id}) }}" onsubmit="return confirm('Confirmer la suppression ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ patient.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/patients/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mb-3">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/patients/by_letter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Patients - Lettre
	{{ letter }}
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Patients - Lettre
			{{ letter }}</h1>

		<table class="table">
			<thead>
				<tr>
					<th>Prénom</th>
					<th>Nom</th>
					<th>Date de naissance</th>
					<th>Voir</th>
					<th>Éditer</th>
					<th>Supprimer</th>
				</tr>
			</thead>
			<tbody>
				{% for patient in patients %}
					<tr>
						<td>{{ patient.firstName }}</td>
						<td>{{ patient.lastName }}</td>
						<td>{{ patient.birthdate|date('d/m/Y') }}</td>
						<td>
							<a href="{{ path('app_patients_show', {id: patient.id}) }}">Voir</a>
						</td>
						<td>
							<a href="{{ path('app_patients_edit', {id: patient.id}) }}">Éditer</a>
						</td>
						<td>
							<a href="{{ path('app_patients_delete', {id: patient.id}) }}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce dossier ?');">Supprimer</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<a href="{{ path('app_patients_index') }}">Retour à la liste complète</a>
	</div>
{% endblock %}

templates/patients/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Patients
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Modifier le dossier médical</h1>

		{{ form_start(form) }}

		<div class="info-biometrique">
			<h2>Informations biometriques</h2>
			<div>
				{{ form_row(form.lastname) }}
				{{ form_row(form.firstName) }}
				{{ form_row(form.birthdate) }}
				{{ form_row(form.bloodgroup) }}
				{{ form_row(form.size) }}
				{{ form_row(form.weight) }}
			</div>
		</div>
		<hr>
		<div class="info-medicales">
			<h2>Informations médicales</h2>
			<div>
				{{ form_row(form.antMedic) }}
				{{ form_row(form.allergies) }}
				{{ form_row(form.vaccins) }}
				{{ form_row(form.tabac) }}
				{{ form_row(form.alcool) }}
				{{ form_row(form.stupefiants) }}
				{{ form_row(form.sommeil) }}
				{{ form_row(form.alimentation) }}
				{{ form_row(form.activitePhysique) }}
				{{ form_row(form.employeur) }}
			</div>
			<hr>
			<div class="emergency-contacts">
				<h2>Contacts d'urgence</h2>
				<button type="button" class="btn btn-success btn-ajouter" data-collection="#emergency-contacts">Ajouter un contact d'urgence</button>
				<div class="list-group" id="emergency-contacts" data-index="{{ form.emergencyContacts|length > 0 ? form.emergencyContacts|last.vars.name + 1 : 0 }}" data-prototype="{{ form_widget(form.emergencyContacts.vars.prototype)|e('html_attr') }}"></div>
				<div class="emergency-contacts-list">
					{{ form_widget(form.emergencyContacts) }}
					{% for contact in emergencyContacts %}
						<a href="{{ path('app_patients_supprimer_contact', {id: patient.id, contactID: contact.id}) }}" class="btn btn-danger">Supprimer
							{{ contact.firstname }}
							{{contact.lastname}}</a>
					{% endfor %}
				</div>
				{{ form_end(form) }}

				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Modifier le dossier médical</button>
					<a class="btn btn-danger" href="{{ path('app_patients_index') }}">Retour à la liste</a>
				</div>

			</div>
			<script src="{{ asset('js/emergency_contacts.js') }}"></script>
		{% endblock %}

templates/patients/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dossiers Médicaux
{% endblock %}

{% block body %}
	<div class="dossier-med">
		<h1>Dossiers Médicaux</h1>
		<div class="new-patient">
			<a href="{{ path('app_patient_new') }}" class="btn btn-primary">Créer un nouveau dossier médical</a>
		</div>
		<div class="alphabet-container">
			<div class="alphabet">
				{% for letter in letters %}
					<div class="letter">
						<a href="{{ path('app_patients_by_letter', {letter: letter}) }}">{{ letter }}
							-</a>
					</div>
				{% endfor %}
			</div>
		</div>
		<hr>
		<div class="row">
        <div class="w-20">
			<h2>Visite médicale</h2>
			<a href="">certificats médicaux</a>
        </div>
        <div class="w-20">
			<h2>Morgue</h2>
			<a href="">Décédés</a>
		</div>
	</div>
{% endblock %}

templates/patients/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un nouveau dossier médical
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Créer un nouveau dossier médical</h1>

		{{ form_start(form) }}

		<div class="info-biometrique">
			<h2>Informations biometriques</h2>
			<div>
				{{ form_row(form.lastname) }}
				{{ form_row(form.firstName) }}
				{{ form_row(form.birthdate) }}
				{{ form_row(form.bloodgroup) }}
				{{ form_row(form.size) }}
				{{ form_row(form.weight) }}
			</div>
		</div>
		<hr>
		<div class="info-medicales">
			<h2>Informations médicales</h2>
			<div>
				{{ form_row(form.antMedic) }}
				{{ form_row(form.allergies) }}
				{{ form_row(form.vaccins) }}
				{{ form_row(form.tabac) }}
				{{ form_row(form.alcool) }}
				{{ form_row(form.stupefiants) }}
				{{ form_row(form.sommeil) }}
				{{ form_row(form.alimentation) }}
				{{ form_row(form.activitePhysique) }}
				{{ form_row(form.employeur) }}
			</div>
			<hr>
			<div class="emergency-contacts">
				<h2>Contacts d'urgence</h2>
				<button type="button" class="btn btn-success btn-ajouter" data-collection="#emergency-contacts">Ajouter un contact d'urgence</button>
				<div class="list-group" id="emergency-contacts" data-index="{{ form.emergencyContacts|length > 0 ? form.emergencyContacts|last.vars.name + 1 : 0 }}" data-prototype="{{ form_widget(form.emergencyContacts.vars.prototype)|e('html_attr') }}"></div>
				<hr>
			</div>

			<div class="form-actions">
				<button type="submit" class="btn btn-primary">Créer le dossier médical</button>
				<a class="btn btn-danger" href="{{ path('app_patients_index') }}">Retour à la liste</a>
			</div>

			{{ form_end(form) }}
		</div>
		<script src="{{ asset('js/emergency_contacts.js') }}"></script>
	{% endblock %}

templates/patients/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dossier médical de
	{{ patient.firstName }}
	{{ patient.lastName }}
{% endblock %}

{% block body %}
	<div class="dossier-med">
		<h1>Dossier médical de
			{{ patient.firstName }}
			{{ patient.lastName }}</h1>
		<div class="row">
			<div class="w-50">
				<h2>Informations personnelles</h2>
				<p>
					<strong>Prénom :</strong>
					{{ patient.firstName }}</p>
				<p>
					<strong>Nom :</strong>
					{{ patient.lastName }}</p>
				<p>
					<strong>Date de naissance :</strong>
					{{ patient.birthdate|date('d/m/Y') }}</p>
				<p>
					<strong>Groupe sanguin :</strong>
					{{ patient.bloodgroup }}</p>
				<p>
					<strong>Taille :</strong>
					{{ patient.size }}</p>
				<p>
					<strong>Poids :</strong>
					{{ patient.weight }}</p>

				<h2>Informations médicales</h2>
				<p>
					<strong>Antécédents médicaux :</strong>
					{{ patient.antMedic }}</p>
				<p>
					<strong>Allergies :</strong>
					{{ patient.allergies }}</p>
				<p>
					<strong>Vaccins :</strong>
					{{ patient.vaccins }}</p>
				<p>
					<strong>Tabac :</strong>
					{{ patient.tabac }}</p>
				<p>
					<strong>Alcool :</strong>
					{{ patient.alcool }}</p>
				<p>
					<strong>Stupéfiants :</strong>
					{{ patient.stupefiants }}</p>
				<p>
					<strong>Sommeil :</strong>
					{{ patient.sommeil }}</p>
				<p>
					<strong>Alimentation :</strong>
					{{ patient.alimentation }}</p>
				<p>
					<strong>Activité physique :</strong>
					{{ patient.activitePhysique }}</p>
				<p>
					<strong>Employeur :</strong>
					{{ patient.employeur }}</p>

				<h2>Contacts d'urgence</h2>
				<ul>
					{% for contact in patient.emergencyContacts %}
						<li>{{ contact.lastName }}
							-
							{{ contact.firstName }}
							-
							{{ contact.phone }}
							-
							{{ contact.relationship }}
						</li>
					{% endfor %}
				</ul>

			</div>
			<div class="w-50">
				<h2>Visites médicales</h2>
				<ul>
					{# {% for visit in patient.visits %}
																<li>{{ visit.date|date('d/m/Y') }}
																	-
																	{{ visit.description }}</li>
															{% endfor %} #}
				</ul>
			</div>
		</div>
		<div class="actions">
			<a href="{{ path('app_patients_edit', {id: patient.id}) }}" class="btn btn-primary">Éditer</a>
			<a href="{{ path('app_patients_delete', {id: patient.id}) }}" class="btn btn-danger" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce dossier ?');">Supprimer</a>
			<a href="{{ path('app_patients_index') }}" class="btn btn-secondary">Retour à la liste</a>
		</div>
	</div>
{% endblock %}